# @package _global_

defaults:
  - /base
  - /model/gpt2s
  - /dataset/fw_gpt2
  - _self_

opt:
  optimizer: 'adamw'
  opt.batch_size: 512
  opt.peak_lr: 0.0006
  opt.b1: 0.9
  opt.b2: 0.95
  opt.weight_decay: 0.1
