# @package _global_

defaults:
  - /base
  - /model/lm11m
  - /dataset/fw_gpt2
  - _self_

bs_configs:
  1:
    opt:
      peak_lr: 0.0012
      t1: 60_000
      t2: 10_000_000
  4:
    opt:
      peak_lr: 0.002
      t1: 80_000
      t2: 10_000_000
  16:
    opt:
      peak_lr: 0.003
      t1: 110_000
      t2: 10_000_000
  64:
    opt:
      peak_lr: 0.0045
      t1: 180_000
      t2: 10_000_000
  256:
    opt:
      peak_lr: 0.007
      t1: 740_000
      t2: 10_000_000
  1024:
    opt:
      peak_lr: 0.01
      t1: 3_000_000
      t2: 10_000_000

opt:
  optimizer: 'adamw'