defaults:
  - default
  - _self_

ds_path: '~/datasets/fineweb_gpt2.bin'
num_tokens_train: 10_000_000_000

model:
  D: 1600  # model/embed/qkv dim
  L: 48    # num. block layers
  T: 1024  # context/sequence length
  V: 50257 # vocab size
