defaults:
  - default
  - _self_

ds_path: '~/datasets/fineweb_gpt2_10B.bin'

model:
  D: 768   # model/embed/qkv dim
  F: 3072  # FF inner dimension (4 * D)
  H: 12    # num. attention heads (768 / 12 = 64 dim/head)
  N: 12    # num. block layers
  L: 1024  # context/sequence length
  V: 50257 # vocab size
