defaults:
  - default
  - _self_

ds_path: '~/datasets/fineweb_gpt2_10B.bin'

model:
  D: 768   # model/embed/qkv dim
  L: 12    # num. block layers
  T: 1024  # context/sequence length
  V: 50257 # vocab size
