defaults:
  - default
  - _self_

ds_path: '~/datasets/fineweb_gpt2_10B.bin'
num_tokens_train: 10_000_000_000

model:
  D: 1600  # model/embed/qkv dim
  F: 6400  # FF inner dimension (4 * D)
  H: 25    # num. attention heads (1600 / 25 = 64 dim/head)
  N: 48    # num. block layers
  L: 1024  # context/sequence length
  V: 50257 # vocab size
