defaults:
  - default
  - _self_

batch_size_valid: 1
num_tokens_train: 100_000
num_tokens_valid: 2_048
num_eval_steps: 10
ds_path: '~/datasets/fineweb_gpt2_10B.bin'
wandb_mode: 'offline'

model:
  k: 2
  N: 4
  V: 50257

opt:
  optimizer: 'adamw'
  b1: 0.9
  t2: 1_000_000
  batch_size: 1
  peak_lr: 0.001