defaults:
  - default
  - _self_

batch_size_valid: 8
num_tokens_train: 100_000
num_tokens_valid: 2_048
eval_every_steps: 20
ds_path_train: '/Users/martin/datasets/fineweb_gpt2_2p5B.bin'
ds_path_valid: '/Users/martin/datasets/fineweb_gpt2_2p5B.bin'
wandb_mode: 'offline'

model:
  k: 1
  L: 128

opt:
  microbatch_size: 8
  warmup_steps: 10